<a href="https://colab.research.google.com/github/0mehedihasan/AI-Beginner-to-Advance/blob/main/numpy_basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# *Numpy*

In [6]:
import numpy as np
print(np.__version__)
np.show_config()
Z = np.zeros(10)
print(Z)
Z = np.zeros((10,10))
print("%d bytes" % (Z.size * Z.itemsize))

1.26.4
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /usr/local/include
    lib directory: /usr/local/lib
    name: openblas64
    openblas configuration: USE_64BITINT=1 DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= HASWELL MAX_THREADS=2
    pc file directory: /usr/local/lib/pkgconfig
    version: 0.3.23.dev
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep139863411681952
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.4
Compilers:
  c:
    args: -fno-strict-aliasing
    commands: cc
    linker: ld.bfd
    linker args: -Wl,--strip-debug, -fno-strict-aliasing
    name: gcc
    version: 10.2.1
  c++:
    commands: c++
    linker: ld.bfd
    linker args: -Wl,--strip-debug
    name: gcc
    version: 10.2.1
  cython:
    commands: cython
    linker: cython
    name: cython
   

In [4]:
arr=np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


Create a 0-D array with value 42

In [7]:
arr = np.array(42)

print(arr)

42


Create a 1-D array containing the values 1,2,3,4,5:

In [8]:
arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


Create a 2-D array containing two arrays with the values 1,2,3 and 4,5,6:

In [9]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)

[[1 2 3]
 [4 5 6]]


Create a 3-D array with two 2-D arrays, both containing two arrays with the values 1,2,3 and 4,5,6:

In [10]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


Check how many dimensions the arrays have:

In [11]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


Create an array with 5 dimensions and verify that it has 5 dimensions:

In [12]:
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)


[[[[[1 2 3 4]]]]]
number of dimensions : 5


Get the first element from the following array:

In [13]:
arr = np.array([1, 2, 3, 4])

print(arr[0])

1


Get the second element from the following array.

In [14]:
arr = np.array([1, 2, 3, 4])

print(arr[1])

2


Get third and fourth elements from the following array and add them.

In [15]:
arr = np.array([1, 2, 3, 4])
add=arr[2]+arr[3]
print(add)

7


Access the element on the first row, second column:

In [19]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('2nd element on 1st row: ', arr[1, 1])
print('5th element on 2nd row: ', arr[1, 4])
print('Last element from 2nd dim: ', arr[1, -1])
print('Last element from 2nd dim: ', arr[-1, -1])

2nd element on 1st row:  7
5th element on 2nd row:  10
Last element from 2nd dim:  10
Last element from 2nd dim:  10


Access the third element of the second array of the first array:

In [20]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[0, 1, 2])

6


NumPy Array Slicing


In [23]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])


[2 3 4 5]




```
Slice elements from index 4 to the end of the array:
```



In [24]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[4:])

[5 6 7]
